// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pb/shortrack.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceStatus int32

const (
	ResourceStatus_RESOURCE_INVALID_STATUS ResourceStatus = 0
	ResourceStatus_RESOURCE_ABSENT         ResourceStatus = 1
	ResourceStatus_RESOURCE_ACTIVE         ResourceStatus = 2
	ResourceStatus_RESOURCE_DEGRADED       ResourceStatus = 3
)

// Enum value maps for ResourceStatus.
var (
	ResourceStatus_name = map[int32]string{
		0: "RESOURCE_INVALID_STATUS",
		1: "RESOURCE_ABSENT",
		2: "RESOURCE_ACTIVE",
		3: "RESOURCE_DEGRADED",
	}
	ResourceStatus_value = map[string]int32{
		"RESOURCE_INVALID_STATUS": 0,
		"RESOURCE_ABSENT":         1,
		"RESOURCE_ACTIVE":         2,
		"RESOURCE_DEGRADED":       3,
	}
)

func (x ResourceStatus) Enum() *ResourceStatus {
	p := new(ResourceStatus)
	*p = x
	return p
}

func (x ResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_shortrack_proto_enumTypes[0].Descriptor()
}

func (ResourceStatus) Type() protoreflect.EnumType {
	return &file_pb_shortrack_proto_enumTypes[0]
}

func (x ResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceStatus.Descriptor instead.
func (ResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{0}
}

type PoolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint32                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Status        ResourceStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=shortrack.ResourceStatus" json:"status,omitempty"`
	PoolName      string                 `protobuf:"bytes,3,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	Iqn           string                 `protobuf:"bytes,4,opt,name=iqn,proto3" json:"iqn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolInfo) Reset() {
	*x = PoolInfo{}
	mi := &file_pb_shortrack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolInfo) ProtoMessage() {}

func (x *PoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolInfo.ProtoReflect.Descriptor instead.
func (*PoolInfo) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{0}
}

func (x *PoolInfo) GetPoolId() uint32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *PoolInfo) GetStatus() ResourceStatus {
	if x != nil {
		return x.Status
	}
	return ResourceStatus_RESOURCE_INVALID_STATUS
}

func (x *PoolInfo) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *PoolInfo) GetIqn() string {
	if x != nil {
		return x.Iqn
	}
	return ""
}

type ListPoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsRequest) Reset() {
	*x = ListPoolsRequest{}
	mi := &file_pb_shortrack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsRequest) ProtoMessage() {}

func (x *ListPoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsRequest.ProtoReflect.Descriptor instead.
func (*ListPoolsRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{1}
}

type ListPoolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*PoolInfo            `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsResponse) Reset() {
	*x = ListPoolsResponse{}
	mi := &file_pb_shortrack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsResponse) ProtoMessage() {}

func (x *ListPoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsResponse.ProtoReflect.Descriptor instead.
func (*ListPoolsResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{2}
}

func (x *ListPoolsResponse) GetPools() []*PoolInfo {
	if x != nil {
		return x.Pools
	}
	return nil
}

type GetPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        *uint32                `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3,oneof" json:"pool_id,omitempty"`
	PoolName      *string                `protobuf:"bytes,2,opt,name=pool_name,json=poolName,proto3,oneof" json:"pool_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolRequest) Reset() {
	*x = GetPoolRequest{}
	mi := &file_pb_shortrack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolRequest) ProtoMessage() {}

func (x *GetPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolRequest.ProtoReflect.Descriptor instead.
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{3}
}

func (x *GetPoolRequest) GetPoolId() uint32 {
	if x != nil && x.PoolId != nil {
		return *x.PoolId
	}
	return 0
}

func (x *GetPoolRequest) GetPoolName() string {
	if x != nil && x.PoolName != nil {
		return *x.PoolName
	}
	return ""
}

type CreatePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        *uint32                `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3,oneof" json:"pool_id,omitempty"`
	PoolName      *string                `protobuf:"bytes,2,opt,name=pool_name,json=poolName,proto3,oneof" json:"pool_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePoolRequest) Reset() {
	*x = CreatePoolRequest{}
	mi := &file_pb_shortrack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolRequest) ProtoMessage() {}

func (x *CreatePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolRequest.ProtoReflect.Descriptor instead.
func (*CreatePoolRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePoolRequest) GetPoolId() uint32 {
	if x != nil && x.PoolId != nil {
		return *x.PoolId
	}
	return 0
}

func (x *CreatePoolRequest) GetPoolName() string {
	if x != nil && x.PoolName != nil {
		return *x.PoolName
	}
	return ""
}

type DeletePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint32                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePoolRequest) Reset() {
	*x = DeletePoolRequest{}
	mi := &file_pb_shortrack_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoolRequest) ProtoMessage() {}

func (x *DeletePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoolRequest.ProtoReflect.Descriptor instead.
func (*DeletePoolRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePoolRequest) GetPoolId() uint32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

type VolumeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint32                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	VolumeId      uint32                 `protobuf:"varint,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Status        ResourceStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=shortrack.ResourceStatus" json:"status,omitempty"`
	VolumeName    string                 `protobuf:"bytes,4,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	VolumeSize    uint64                 `protobuf:"varint,5,opt,name=volume_size,json=volumeSize,proto3" json:"volume_size,omitempty"`
	Iqn           string                 `protobuf:"bytes,6,opt,name=iqn,proto3" json:"iqn,omitempty"`
	Lun           int64                  `protobuf:"varint,7,opt,name=lun,proto3" json:"lun,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeInfo) Reset() {
	*x = VolumeInfo{}
	mi := &file_pb_shortrack_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeInfo) ProtoMessage() {}

func (x *VolumeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeInfo.ProtoReflect.Descriptor instead.
func (*VolumeInfo) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{6}
}

func (x *VolumeInfo) GetPoolId() uint32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *VolumeInfo) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *VolumeInfo) GetStatus() ResourceStatus {
	if x != nil {
		return x.Status
	}
	return ResourceStatus_RESOURCE_INVALID_STATUS
}

func (x *VolumeInfo) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *VolumeInfo) GetVolumeSize() uint64 {
	if x != nil {
		return x.VolumeSize
	}
	return 0
}

func (x *VolumeInfo) GetIqn() string {
	if x != nil {
		return x.Iqn
	}
	return ""
}

func (x *VolumeInfo) GetLun() int64 {
	if x != nil {
		return x.Lun
	}
	return 0
}

type ListVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint32                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_pb_shortrack_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{7}
}

func (x *ListVolumesRequest) GetPoolId() uint32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

type ListVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*VolumeInfo          `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesResponse) Reset() {
	*x = ListVolumesResponse{}
	mi := &file_pb_shortrack_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesResponse) ProtoMessage() {}

func (x *ListVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListVolumesResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{8}
}

func (x *ListVolumesResponse) GetVolumes() []*VolumeInfo {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type GetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint32                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	VolumeId      *uint32                `protobuf:"varint,2,opt,name=volume_id,json=volumeId,proto3,oneof" json:"volume_id,omitempty"`
	VolumeName    *string                `protobuf:"bytes,3,opt,name=volume_name,json=volumeName,proto3,oneof" json:"volume_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeRequest) Reset() {
	*x = GetVolumeRequest{}
	mi := &file_pb_shortrack_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeRequest) ProtoMessage() {}

func (x *GetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{9}
}

func (x *GetVolumeRequest) GetPoolId() uint32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *GetVolumeRequest) GetVolumeId() uint32 {
	if x != nil && x.VolumeId != nil {
		return *x.VolumeId
	}
	return 0
}

func (x *GetVolumeRequest) GetVolumeName() string {
	if x != nil && x.VolumeName != nil {
		return *x.VolumeName
	}
	return ""
}

type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint32                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	VolumeId      *uint32                `protobuf:"varint,2,opt,name=volume_id,json=volumeId,proto3,oneof" json:"volume_id,omitempty"`
	VolumeName    *string                `protobuf:"bytes,3,opt,name=volume_name,json=volumeName,proto3,oneof" json:"volume_name,omitempty"`
	VolumeSize    uint64                 `protobuf:"varint,4,opt,name=volume_size,json=volumeSize,proto3" json:"volume_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_pb_shortrack_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{10}
}

func (x *CreateVolumeRequest) GetPoolId() uint32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *CreateVolumeRequest) GetVolumeId() uint32 {
	if x != nil && x.VolumeId != nil {
		return *x.VolumeId
	}
	return 0
}

func (x *CreateVolumeRequest) GetVolumeName() string {
	if x != nil && x.VolumeName != nil {
		return *x.VolumeName
	}
	return ""
}

func (x *CreateVolumeRequest) GetVolumeSize() uint64 {
	if x != nil {
		return x.VolumeSize
	}
	return 0
}

type DeleteVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint32                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	VolumeId      uint32                 `protobuf:"varint,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_pb_shortrack_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortrack_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortrack_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteVolumeRequest) GetPoolId() uint32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *DeleteVolumeRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

var File_pb_shortrack_proto protoreflect.FileDescriptor

const file_pb_shortrack_proto_rawDesc = "" +
	"\n" +
	"\x12pb/shortrack.proto\x12\tshortrack\"\x85\x01\n" +
	"\bPoolInfo\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\rR\x06poolId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.shortrack.ResourceStatusR\x06status\x12\x1b\n" +
	"\tpool_name\x18\x03 \x01(\tR\bpoolName\x12\x10\n" +
	"\x03iqn\x18\x04 \x01(\tR\x03iqn\"\x12\n" +
	"\x10ListPoolsRequest\">\n" +
	"\x11ListPoolsResponse\x12)\n" +
	"\x05pools\x18\x01 \x03(\v2\x13.shortrack.PoolInfoR\x05pools\"j\n" +
	"\x0eGetPoolRequest\x12\x1c\n" +
	"\apool_id\x18\x01 \x01(\rH\x00R\x06poolId\x88\x01\x01\x12 \n" +
	"\tpool_name\x18\x02 \x01(\tH\x01R\bpoolName\x88\x01\x01B\n" +
	"\n" +
	"\b_pool_idB\f\n" +
	"\n" +
	"_pool_name\"m\n" +
	"\x11CreatePoolRequest\x12\x1c\n" +
	"\apool_id\x18\x01 \x01(\rH\x00R\x06poolId\x88\x01\x01\x12 \n" +
	"\tpool_name\x18\x02 \x01(\tH\x01R\bpoolName\x88\x01\x01B\n" +
	"\n" +
	"\b_pool_idB\f\n" +
	"\n" +
	"_pool_name\",\n" +
	"\x11DeletePoolRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\rR\x06poolId\"\xdb\x01\n" +
	"\n" +
	"VolumeInfo\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\rR\x06poolId\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\rR\bvolumeId\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.shortrack.ResourceStatusR\x06status\x12\x1f\n" +
	"\vvolume_name\x18\x04 \x01(\tR\n" +
	"volumeName\x12\x1f\n" +
	"\vvolume_size\x18\x05 \x01(\x04R\n" +
	"volumeSize\x12\x10\n" +
	"\x03iqn\x18\x06 \x01(\tR\x03iqn\x12\x10\n" +
	"\x03lun\x18\a \x01(\x03R\x03lun\"-\n" +
	"\x12ListVolumesRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\rR\x06poolId\"F\n" +
	"\x13ListVolumesResponse\x12/\n" +
	"\avolumes\x18\x01 \x03(\v2\x15.shortrack.VolumeInfoR\avolumes\"\x91\x01\n" +
	"\x10GetVolumeRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\rR\x06poolId\x12 \n" +
	"\tvolume_id\x18\x02 \x01(\rH\x00R\bvolumeId\x88\x01\x01\x12$\n" +
	"\vvolume_name\x18\x03 \x01(\tH\x01R\n" +
	"volumeName\x88\x01\x01B\f\n" +
	"\n" +
	"_volume_idB\x0e\n" +
	"\f_volume_name\"\xb5\x01\n" +
	"\x13CreateVolumeRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\rR\x06poolId\x12 \n" +
	"\tvolume_id\x18\x02 \x01(\rH\x00R\bvolumeId\x88\x01\x01\x12$\n" +
	"\vvolume_name\x18\x03 \x01(\tH\x01R\n" +
	"volumeName\x88\x01\x01\x12\x1f\n" +
	"\vvolume_size\x18\x04 \x01(\x04R\n" +
	"volumeSizeB\f\n" +
	"\n" +
	"_volume_idB\x0e\n" +
	"\f_volume_name\"K\n" +
	"\x13DeleteVolumeRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\rR\x06poolId\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\rR\bvolumeId*n\n" +
	"\x0eResourceStatus\x12\x1b\n" +
	"\x17RESOURCE_INVALID_STATUS\x10\x00\x12\x13\n" +
	"\x0fRESOURCE_ABSENT\x10\x01\x12\x13\n" +
	"\x0fRESOURCE_ACTIVE\x10\x02\x12\x15\n" +
	"\x11RESOURCE_DEGRADED\x10\x032\xa9\x04\n" +
	"\x05Sigma\x12F\n" +
	"\tListPools\x12\x1b.shortrack.ListPoolsRequest\x1a\x1c.shortrack.ListPoolsResponse\x129\n" +
	"\aGetPool\x12\x19.shortrack.GetPoolRequest\x1a\x13.shortrack.PoolInfo\x12?\n" +
	"\n" +
	"CreatePool\x12\x1c.shortrack.CreatePoolRequest\x1a\x13.shortrack.PoolInfo\x12?\n" +
	"\n" +
	"DeletePool\x12\x1c.shortrack.DeletePoolRequest\x1a\x13.shortrack.PoolInfo\x12L\n" +
	"\vListVolumes\x12\x1d.shortrack.ListVolumesRequest\x1a\x1e.shortrack.ListVolumesResponse\x12?\n" +
	"\tGetVolume\x12\x1b.shortrack.GetVolumeRequest\x1a\x15.shortrack.VolumeInfo\x12E\n" +
	"\fCreateVolume\x12\x1e.shortrack.CreateVolumeRequest\x1a\x15.shortrack.VolumeInfo\x12E\n" +
	"\fDeleteVolume\x12\x1e.shortrack.DeleteVolumeRequest\x1a\x15.shortrack.VolumeInfoB!Z\x1fgithub.com/sapslaj/shortrack/pbb\x06proto3"

var (
	file_pb_shortrack_proto_rawDescOnce sync.Once
	file_pb_shortrack_proto_rawDescData []byte
)

func file_pb_shortrack_proto_rawDescGZIP() []byte {
	file_pb_shortrack_proto_rawDescOnce.Do(func() {
		file_pb_shortrack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_shortrack_proto_rawDesc), len(file_pb_shortrack_proto_rawDesc)))
	})
	return file_pb_shortrack_proto_rawDescData
}

var file_pb_shortrack_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_shortrack_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_shortrack_proto_goTypes = []any{
	(ResourceStatus)(0),         // 0: shortrack.ResourceStatus
	(*PoolInfo)(nil),            // 1: shortrack.PoolInfo
	(*ListPoolsRequest)(nil),    // 2: shortrack.ListPoolsRequest
	(*ListPoolsResponse)(nil),   // 3: shortrack.ListPoolsResponse
	(*GetPoolRequest)(nil),      // 4: shortrack.GetPoolRequest
	(*CreatePoolRequest)(nil),   // 5: shortrack.CreatePoolRequest
	(*DeletePoolRequest)(nil),   // 6: shortrack.DeletePoolRequest
	(*VolumeInfo)(nil),          // 7: shortrack.VolumeInfo
	(*ListVolumesRequest)(nil),  // 8: shortrack.ListVolumesRequest
	(*ListVolumesResponse)(nil), // 9: shortrack.ListVolumesResponse
	(*GetVolumeRequest)(nil),    // 10: shortrack.GetVolumeRequest
	(*CreateVolumeRequest)(nil), // 11: shortrack.CreateVolumeRequest
	(*DeleteVolumeRequest)(nil), // 12: shortrack.DeleteVolumeRequest
}
var file_pb_shortrack_proto_depIdxs = []int32{
	0,  // 0: shortrack.PoolInfo.status:type_name -> shortrack.ResourceStatus
	1,  // 1: shortrack.ListPoolsResponse.pools:type_name -> shortrack.PoolInfo
	0,  // 2: shortrack.VolumeInfo.status:type_name -> shortrack.ResourceStatus
	7,  // 3: shortrack.ListVolumesResponse.volumes:type_name -> shortrack.VolumeInfo
	2,  // 4: shortrack.Sigma.ListPools:input_type -> shortrack.ListPoolsRequest
	4,  // 5: shortrack.Sigma.GetPool:input_type -> shortrack.GetPoolRequest
	5,  // 6: shortrack.Sigma.CreatePool:input_type -> shortrack.CreatePoolRequest
	6,  // 7: shortrack.Sigma.DeletePool:input_type -> shortrack.DeletePoolRequest
	8,  // 8: shortrack.Sigma.ListVolumes:input_type -> shortrack.ListVolumesRequest
	10, // 9: shortrack.Sigma.GetVolume:input_type -> shortrack.GetVolumeRequest
	11, // 10: shortrack.Sigma.CreateVolume:input_type -> shortrack.CreateVolumeRequest
	12, // 11: shortrack.Sigma.DeleteVolume:input_type -> shortrack.DeleteVolumeRequest
	3,  // 12: shortrack.Sigma.ListPools:output_type -> shortrack.ListPoolsResponse
	1,  // 13: shortrack.Sigma.GetPool:output_type -> shortrack.PoolInfo
	1,  // 14: shortrack.Sigma.CreatePool:output_type -> shortrack.PoolInfo
	1,  // 15: shortrack.Sigma.DeletePool:output_type -> shortrack.PoolInfo
	9,  // 16: shortrack.Sigma.ListVolumes:output_type -> shortrack.ListVolumesResponse
	7,  // 17: shortrack.Sigma.GetVolume:output_type -> shortrack.VolumeInfo
	7,  // 18: shortrack.Sigma.CreateVolume:output_type -> shortrack.VolumeInfo
	7,  // 19: shortrack.Sigma.DeleteVolume:output_type -> shortrack.VolumeInfo
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pb_shortrack_proto_init() }
func file_pb_shortrack_proto_init() {
	if File_pb_shortrack_proto != nil {
		return
	}
	file_pb_shortrack_proto_msgTypes[3].OneofWrappers = []any{}
	file_pb_shortrack_proto_msgTypes[4].OneofWrappers = []any{}
	file_pb_shortrack_proto_msgTypes[9].OneofWrappers = []any{}
	file_pb_shortrack_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_shortrack_proto_rawDesc), len(file_pb_shortrack_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_shortrack_proto_goTypes,
		DependencyIndexes: file_pb_shortrack_proto_depIdxs,
		EnumInfos:         file_pb_shortrack_proto_enumTypes,
		MessageInfos:      file_pb_shortrack_proto_msgTypes,
	}.Build()
	File_pb_shortrack_proto = out.File
	file_pb_shortrack_proto_goTypes = nil
	file_pb_shortrack_proto_depIdxs = nil
}
